on: push
jobs:
  build-dawn:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: git clone https://dawn.googlesource.com/dawn

      - name: Build
        working-directory: dawn
        run: |
          node ../scripts/write-dawn-cmake-command.ts cmake-command.txt
          $(cat cmake-command.txt)
          cmake --build out/Release
          cmake --install out/Release --prefix install/Release
          ls -alrt install/Release
