on: push
jobs:
  build-dawn:
    runs-on: macos-latest
    steps:
      - run: |
          git clone https://dawn.googlesource.com/dawn
          cd dawn
          cmake -S . -B out/Release -DDAWN_FETCH_DEPENDENCIES=ON -DDAWN_ENABLE_INSTALL=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build out/Release
          cmake --install out/Release --prefix install/Release
          ls -alrt install/Release
