name: Build Dawn
on: push
jobs:
  build-dawn:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15]

    name: Build Dawn on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Dawn repository
        run: git clone --depth=1 https://dawn.googlesource.com/dawn

      - name: Configure CMake
        working-directory: dawn
        run: >
          cmake -S . -B out/Release
          -DDAWN_FETCH_DEPENDENCIES=ON
          -DDAWN_ENABLE_INSTALL=ON
          -DDAWN_BUILD_MONOLITHIC_LIBRARY=SHARED
          -DDAWN_BUILD_SAMPLES=OFF
          -DDAWN_BUILD_PROTOBUF=OFF
          -DTINT_BUILD_CMD_TOOLS=OFF
          -DTINT_BUILD_TESTS=OFF
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: dawn
        run: cmake --build out/Release --target webgpu_dawn

      - name: Package
        working-directory: dawn
        run: |
          cmake --install out/Release --prefix dawn-${{ matrix.os}}
          cmake -E tar cvzf dawn-${{ matrix.os}}.tar.gz dawn-${{ matrix.os}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dawn-${{ matrix.os}}
          path: dawn/dawn-${{ matrix.os}}.tar.gz
