name: Build Dawn
on: push
jobs:
  build-dawn:
    name: Build Dawn
    runs-on: macos-14
    steps:
      - name: Clone Dawn Repository
        run: git clone https://dawn.googlesource.com/dawn

      - name: Configure CMake
        working-directory: dawn
        run: >
          cmake -S . -B out/Release
          -DDAWN_FETCH_DEPENDENCIES=ON
          -DDAWN_ENABLE_INSTALL=ON
          -DCMAKE_BUILD_TYPE=Release
          -DDAWN_BUILD_PROTOBUF=OFF

      - name: Build
        working-directory: dawn
        run: cmake --build out/Release

      - name: Package
        working-directory: dawn
        run: |
          cmake --install out/Release --prefix Dawn-macos-14
          cmake -E tar cvzf Dawn-macos-14.tar.gz Dawn-macos-14
