name: Build Dawn
on: push
jobs:
  build-dawn:
    name: Build Dawn
    runs-on: macos-15
    steps:
      - name: Clone Dawn Repository
        run: git clone --depth=1 https://dawn.googlesource.com/dawn

      - name: Configure CMake
        working-directory: dawn
        run: >
          cmake -S . -B out/Release
          -DDAWN_FETCH_DEPENDENCIES=ON
          -DDAWN_ENABLE_INSTALL=ON
          -DDAWN_BUILD_MONOLITHIC_LIBRARY=SHARED
          -DDAWN_BUILD_SAMPLES=OFF
          -DDAWN_BUILD_PROTOBUF=OFF
          -DTINT_BUILD_CMD_TOOLS=OFF
          -DTINT_BUILD_TESTS=OFF
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: dawn
        run: cmake --build out/Release

      - name: Package
        working-directory: dawn
        run: |
          cmake --install out/Release --prefix Dawn-macos-15
          cmake -E tar cvzf Dawn-macos-15.tar.gz Dawn-macos-15

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dawn-macos-15
          path: Dawn-macos-15.tar.gz
