name: Build Dawn
on: push
jobs:
  build-dawn:
    name: Build Dawn
    runs-on: macos-14
    steps:
      - name: Clone Dawn Repository
        run: git clone --depth=1 https://dawn.googlesource.com/dawn

      - name: Configure CMake
        working-directory: dawn
        run: >
          cmake -S . -B out/Release
          -DDAWN_FETCH_DEPENDENCIES=ON
          -DDAWN_BUILD_SAMPLES=OFF
          -DDAWN_BUILD_PROTOBUF=OFF
          -DTINT_BUILD_CMD_TOOLS=OFF
          -DTINT_BUILD_TESTS=OFF
          -DDAWN_ENABLE_INSTALL=ON
          -DCMAKE_CXX_STANDARD=20
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: dawn
        run: cmake --build out/Release --target dawn_native

      - name: Package
        working-directory: dawn
        run: |
          cmake --install out/Release --config Release --prefix Dawn-macos-14
          cmake -E tar cvzf Dawn-macos-14.tar.gz Dawn-macos-14
