name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - run: pnpm dawn:get
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm dawn:gen

      - run: pnpm i

      - run: CXX=clang++ pnpx node-gyp rebuild

      - run: strings dawn-binaries/lib/libwebgpu_dawn.so | grep GLIBCXX

      - run: strings build/Release/dawn.node | grep GLIBCXX

      - run: pnpm test
